### ISSUE TITLE
Missing required param: type.

### ISSUE THREAD

**Issue by ThreeWest** [adam-stripe/stripe-connect-managed-rails#2]
Hi There,

I am testing out your example app and I'm running into an issue where I was getting an error "Missing required param: type."

I looks like it just needed some minor changes in the stripe_accounts_controller:
Remove "managed: true,"
Add "type: 'custom'," where "managed: true" used to be.  *Do not remove type from legal_entity. Both are needed.

I guess this was due to API changes but I thought I'd add it here in case anyone else was running into the same issue.

**Comment by ThreeWest** [comment]
THANK YOU for this by they way! I'm learning a lot of new things from you code.

**Comment by adam-stripe** [comment]
Hey @ThreeWest, glad to hear this has been helpful! 

You're right that this was due to a difference in the API version — this example uses the 2016-07-06 version, which (as you mentioned) accepts a `managed` param instead of `type` (this was updated in https://stripe.com/docs/upgrades#2017-05-25). 

In any case, since this API version is ~a year and a half old (😬 ) I'll plan on updating in the coming months as time allows. Closing for now, but thanks for flagging!

**Comment by ArisNance** [comment]
Thanks for the post @ThreeWest. I ran into this issue today and no idea what to do about it. Best!
